[platformio]
default_envs = xiao_esp32s3_sense
src_dir = main

[env:xiao_esp32s3_sense]
platform = espressif32@6.13.0
board = seeed_xiao_esp32s3
framework = espidf
monitor_speed = 115200
board_build.flash_size = 8MB
board_build.psram_type = opi
board_build.partitions = partitions.csv
